export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CATEGORIES_WERE_FETCHED = 'CATEGORIES_WERE_FETCHED';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const CATEGORY_WINNER_WAS_CHOSEN = 'CATEGORY_WINNER_WAS_CHOSEN';
