export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const CATEGORY_WAS_FETCHED = 'CATEGORY_WAS_FETCHED';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const GET_CATEGORIES_ERROR = 'GET_CATEGORIES_ERROR';
export const CATEGORY_WAS_SELECTED = 'CATEGORY_WAS_SELECTED';
export const CATEGORY_WAS_DESELECTED = 'CATEGORY_WAS_DESELECTED';